filter:
  excluded_paths:
    - vendor/
    - trash/

build:
  environment:
    php:
      version: 8.0
      pecl_extensions:
        - ds
      ini:
        "date.timezone": "UTC"
        "opcache.enable_cli": 1
        "opcache.enable": 1
        "extension": "ds.so"
  dependencies:
    override:
      - composer install --prefer-dist --no-progress --classmap-authoritative
  nodes:
    analysis:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml
            coverage:
              file: build/coverage/clover.xml
              format: php-clover
          - command: php-scrutinizer-run

checks:
  php: true
