name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["8.0"]
    env:
      extensions: opcache, mbstring, ds, pcov
      tools: composer
      ini-values: opcache.enable_cli = 1, precision=16, default_charset='UTF-8', pcov.directory=components
      key: cache-1608571128502
    name: PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: ${{ env.ini-values }}
          coverage: pcov
          tools: ${{ env.tools }}
        env:
          fail-fast: true

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Validate composer
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --classmap-authoritative --ignore-platform-reqs

      # - name: Run Psalm
      #   run: vendor/bin/psalm --output-format=github

      - name: Run tests with phpunit
        run: vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: build/coverage/clover.xml
          fail_ci_if_error: false

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}}
